apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-nginx-policy
  namespace: ingress-nginx
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx

  ingress:
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: grafanadashboard
            app.kubernetes.io/name: grafana
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

  egress:

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: argocd
            app.kubernetes.io/name: argocd-server
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP


    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: istio-system
            app.kubernetes.io/name: istio-ingress
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: loki
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP


    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: jaeger
            app.kubernetes.io/name: jaeger
            app.kubernetes.io/component: query
      toPorts:
        - ports:
            - port: "16686"
              protocol: TCP


    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: victoriametrics
            app.kubernetes.io/name: vmalertmanager
      toPorts:
        - ports:
            - port: "9093"
              protocol: TCP


    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: victoriametrics
            app.kubernetes.io/name: vmselect
      toPorts:
        - ports:
            - port: "8481"
              protocol: TCP


    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: velero
            app.kubernetes.io/name: velero-ui
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP


    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            app.kubernetes.io/name: hubble-ui
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP


    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: falco
            app.kubernetes.io/name: falcosidekick
      toPorts:
        - ports:
            - port: "2802"
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP

          rules:
            dns:
              - matchPattern: "*"