apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prometheus-cert-kv
  namespace: monitoring
spec:
  provider: azure
  secretObjects:
    - secretName: tls-prometheus-kv
      type: kubernetes.io/tls
      data:
        - objectName: PrometheusDashboardCertificate
          key: tls.key
        - objectName: PrometheusDashboardCertificate
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    clientID: "980fd6bd-d343-405c-a52e-79c8418a2d90"
    keyvaultName: "my-secure-keyvault-aks"
    tenantId: "604f1a96-cbe8-43f8-abbf-f8eaf5d85730"
    objects: |
      array:
        - |
          objectName: PrometheusDashboardCertificate
          objectType: secret
          objectVersion: ""