apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-service-deployment.yaml
  - book-services-deployment.yaml
  - book-transaction-service-deployment.yaml
  - feedback-service-deployment.yaml
  - notification-service-deployment.yaml
  - security-service-deployment.yaml
  - upload-file-service-deployment.yaml
  - ../Tools
  - ../DB
images:
  - name: yassmineljeri/config-service
    newTag: v1.5.1
  - name: yassmineljeri/book-service
    newTag: v1.1.5
  - name: yassmineljeri/book-transaction-service
    newTag: v1.1.0
  - name: yassmineljeri/feedback-service
    newTag: v1.1.0
  - name: yassmineljeri/notification-service
    newTag: v1.1.0
  - name: yassmineljeri/security-service
    newTag: v1.1.0
  - name: yassmineljeri/upload-file-service
    newTag: v1.1.0
