apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-service-deployment.yaml
  - book-service-deployment.yaml
  - book-transaction-service-deployment.yaml
  - feedback-service-deployment.yaml
  - notification-service-deployment.yaml
  - security-service-deployment.yaml
  - upload-file-service-deployment.yaml
  - ../Tools
  - ../DB
images:
  - name: registrybsn.azurecr.io/config-service
    newTag: v1.5.9
  - name: registrybsn.azurecr.io/book-services
    newTag: v1.1.2
  - name: registrybsn.azurecr.io/book-transaction-service
    newTag: v1.1.2
  - name: registrybsn.azurecr.io/feedback-service
    newTag: v1.1.2
  - name: registrybsn.azurecr.io/notification-service
    newTag: v1.1.0
  - name: registrybsn.azurecr.io/security-service
    newTag: v1.1.0
  - name: registrybsn.azurecr.io/upload-file-service
    newTag: v1.1.0