image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.89.0"
  pullPolicy: IfNotPresent

mode: deployment

config:
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_mib: 200
      spike_limit_mib: 20

  exporters:
    # Traces -> Jaeger
    otlp/jaeger:
      endpoint: jaeger-collector.jaeger.svc.cluster.local:14250
      tls:
        insecure: true

    # Metrics -> VictoriaMetrics
    otlphttp/vm:
      endpoint: http://vminsert-vmks-victoria-metrics-k8s-stack.victoriametrics.svc.cluster.local:8480/insert/0/opentelemetry
      tls:
        insecure: true

    # Logs -> Loki
    loki:
      endpoint: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
      tls:
        insecure: true
      headers:
        X-Scope-OrgID: "foo"

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch, memory_limiter]
        exporters: [otlp/jaeger]

      metrics:
        receivers: [otlp]
        processors: [batch, memory_limiter]
        exporters: [otlphttp/vm]

      logs:
        receivers: [otlp]
        processors: [batch, memory_limiter]
        exporters: [loki]



#helm upgrade otel-collector open-telemetry/opentelemetry-collector   -n opentelemetry -f opentelemtry-values.yaml