image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.89.0"
  pullPolicy: IfNotPresent

mode: deployment

config:
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
    basicauth/loki:
      client_auth:
        username: loki
        password: loki

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    # ⬇️ Drop noisy health/readiness/liveness spans
    filter/drop_health:
      error_mode: ignore
      traces:
        span:
          - 'attributes["http.target"] != nil and IsMatch(attributes["http.target"], "^/(actuator/)?health(/.*)?$")'
          - 'attributes["http.route"]  != nil and IsMatch(attributes["http.route"],  "^/(actuator/)?health(/.*)?$")'
          - 'name != nil and IsMatch(name, "^GET /(actuator/)?health(/.*)?$")'
          - 'attributes["http.target"] != nil and IsMatch(attributes["http.target"], "^/(livez|readyz)$")'
    memory_limiter:
      check_interval: 5s
      limit_mib: 200
      spike_limit_mib: 20
    batch: {}

  exporters:
    otlp/jaeger:
      endpoint: jaeger-collector.jaeger.svc.cluster.local:4317
      tls:
        insecure: true

    otlphttp/vm:
      endpoint: http://vminsert-vmks-victoria-metrics-k8s-stack.victoriametrics.svc.cluster.local:8480/insert/0/opentelemetry
      tls:
        insecure: true

    loki:
      endpoint: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
      tls:
        insecure: true
      auth:
        authenticator: basicauth/loki
      headers:
        X-Scope-OrgID: "foo"

  service:
    extensions: [health_check, basicauth/loki]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [filter/drop_health, memory_limiter, batch]
        exporters: [otlp/jaeger]

      metrics:
        receivers: [otlp]
        processors: [batch, memory_limiter]
        exporters: [otlphttp/vm]

      logs:
        receivers: [otlp]
        processors: [batch, memory_limiter]
        exporters: [loki]

  # helm upgrade --install otel-collector open-telemetry/opentelemetry-collector   -n opentelemetry -f opentelemtry-values.yaml