apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-secrets-deployment
  namespace: devops-agent
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pull-secrets
  template:
    metadata:
      labels:
        app: pull-secrets
    spec:
      restartPolicy: Always
      serviceAccountName: keyvault-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-devops-agent-secrets
      containers:
        - name: secret-writer
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for CSI secrets..."
              while [ ! -f /mnt/secrets-store/AzpToken ]; do echo "Waiting..."; sleep 3; done
              echo "Secrets ready. Done."
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
